from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [str(Dir('#')), cwd]

path =  [cwd]
path += [cwd + '/key']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
